version: '3.6'

networks:
  wiremock-network:
    name: wiremock-network
    driver: bridge

services:

  wiremock-server:
    build:
      context: ./wiremock
    image: wiremock-server:latest
    ports:
      - 9000:9000
    networks:
      - wiremock-network

  haproxy:
    image: haproxy:2.1.3-alpine
    ports:
      - 3128:3128
    volumes:
      - ${PWD}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - wiremock-network